lua/nvim-web-devicons.lua
provide `nvim-web-devicon.default_icon` and remove it from the `get_icon` so users can choose if they want one (returning nil in this case)
=> remove default icon

lua/nvim-web-devicons.lua
@kyazdani42 this PR changes the way we handle the default icon, it adds in a 3rd optional argument to `get_icon` which are options. For now the only option is `default = boolean` if true then the get icon will return the default icon if none if found. This way a user can still opt not to return a default.
so usage will be
```lua
-- No default
require'nvim-web-devicons'.get_icon("filename.js", "js")
-- Or with default
require'nvim-web-devicons'.get_icon("filename.js", "js", { default = true })
```
I think this is preferable to just removing it and adding the default to exports because by removing it it means you won't be able to get the `highlight name` for the default icon. The default icon's name is `Default` but the highlight group is added when `get_highlight_name` is called so it's …
=> Add an options table so we can choose to return a default

lua/nvim-web-devicons.lua
@kyazdani42 this was causing the plugin to break in svg files as the icon key was
incorrectly named but being accessed. As for the other icon I removed that was a duplicate I didn't notice when I made the original PR
=> Fix svg icon key name

README.md, lua/nvim-web-devicons.lua
This will allow user to enable default icon globally. It will benefit plugins like [telescope](https://github.com/nvim-lua/telescope.nvim) (and some other plugins who uses devicons) so you don't have to configure it for each plugin.
=> feat: option to globally enable default icon

lua/nvim-web-devicons.lua
C currently has a grey shade associated to it. It's probably best to not give unsaturated colors to primary languages (as opposed to config files such as gitignore, makefile, etc) because next to a saturated color, it doesn't carry the fact that both informations have the same importance.
Before:
After:
=> fix: adjust c-lang color

lua/nvim-web-devicons.lua
Adds an orange tint (taken directly from the GitLab logo) to the `.gitlab-ci.yml` icon.
=> Add color for .gitlab-ci.yml

README.md, lua/nvim-web-devicons.lua
Hey!
I would like to import all of the icons in my configuration. The use case is to create my own highlight groups for the statusline with a background color:
```lua
local icons = require('nvim-web-devicons').get_icons()
for _, icon_data in pairs(icons) do
if icon_data.color and icon_data.name then
local hl_group = icon_data.name and 'StatuslineDevIcon' .. icon_data.name
if hl_group then
vim.api.nvim_command("highlight! "..hl_group.. " guifg="..icon_data.color.." guibg="..statusline_background)
end
end
end
```
What do you think of this? Should I add the `get_icons` function to the docs, or is it okay to keep it a "hidden" feature?
=> feat: allow importing all icons

lua/nvim-web-devicons.lua
Hey!
Colorschemes usually run `highlight clear` to clear all highlights before applying their own. This means that if the colorscheme is changed *after* this plugin is initialized, all highlight groups would be lost.
The solution would be to also create the highlights as a response to the `ColorScheme` `autocmd`.
Example of the problem:
https://user-images.githubusercontent.com/9450943/113504038-413d9d00-953e-11eb-8f7d-b68c2471dfe1.mov
Does this solution make sense for this plugin? Also, I wasn't sure if I should wrap the `autocmd` in an `augroup` or not in this case. What do you think?
=> Avoid highlights being overridden when setting a colorscheme after setup()

lua/nvim-web-devicons.lua
[Such names](https://www.gnu.org/licenses/gpl-howto.html) are commonly used for the GPL license.
=> Add COPYING license icon

lua/nvim-web-devicons.lua
`CMakeLists.txt` had an incorrect case (what caused the default icon on Linux).
Also I added `cmake` rule for `.cmake` files (CMake scripts).
=> Fix CMake icon

lua/nvim-web-devicons.lua
This PR adds icons that usually used in [Godot](https://godotengine.org/) (open source game engine) project. It contains some engine-specific formats and common media files (fonts, 3d models, music, etc.).
=> Add Godot icons

lua/nvim-web-devicons.lua
The colors and icons are the same as for the OCaml's `.ml` and `.mli` files.
=> Add icons for the .sml and .sig file extensions used by Standard ML

lua/nvim-web-devicons.lua
There isn't a proper icon in nerdfont yet, so just using a black
hexagon, which is pretty close to the favicon on
https://crystal-lang.org though not at the correct angle.
=> Add icon for Crystal

lua/nvim-web-devicons.lua
Simple fix that was causing a lot of problems with another plugin, fzf-lua, and probably others.  If setup gets called multiple times, the icon map names can get clobbered and quit matching extensions properly.
=> Fix bug caused by multiple setup calls clobbering icon map names

lua/nvim-web-devicons.lua
If there is no ext, it will automatically read from name.
=> Make ext not a required arg

lua/nvim-web-devicons.lua
Updated the Puppet icon and color and added the same for Puppet .epp files﻿
This is dependent on the following PR in ryanoasis/nerd-fonts: https://github.com/ryanoasis/nerd-fonts/pull/652
=> Update the puppet icon(s)

lua/nvim-web-devicons.lua
Description:
Nim is a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula.
WWW: https://nim-lang.org/
The nim's logo is a [gold crown](https://nim-lang.org/assets/img/logo.svg), so I used the crown Unicode symbol, with the standard color of nim, and “gold” color for cterm.
Thanks.
=> Add icon for .nim

README.md, lua/nvim-web-devicons.lua
Adds the `filetypes` table, which is a map from vim filetypes to icon names.
```lua
local filetypes = {
["Brewfile"] = "Brewfile",
["COMMIT"] = "COMMIT_EDITMSG",
["COPYING"] = "COPYING",
-- ...
["yaml"] = "yaml",
["zig"] = "zig",
["zsh"] = "zsh",
}
```
The map is not exhaustive. More filetypes should be added over time, but at least this is a start.
Also adds the following functions:
```lua
get_icon_by_filetype(filetype, opts)
get_icon_colors_by_filetype(filetype, opts)
get_icon_color_by_filetype(filetype, opts)
get_icon_cterm_color_by_filetype(filetype, opts)
get_icon_name_by_filetype(filetype)
``` 
Because some icons are not distinguishable by their filetype alone, the filetype table maps to the "most common" or "canonical" icon. E.g. the filetype `cpp` maps to the `cpp` icon, even …
=> feat: get icons by filetype

lua/nvim-web-devicons.lua
My last PR (#125) was partially broken 😬 
When getting icons by filetype, if the filetype was not found in the filetypes map, `nil` was being returned immediately. This led to `opts.default` being ignored. This PR should fix that issue.
=> Fix: _by_filetype functions should return default icon when opts.default is true

lua/nvim-web-devicons.lua
`get_icon_color` doesn't respect if icon colors are set via highlight groups. If a foreground or ctermfg is not set in the highlight group it will fall back to the information in the  icon data.
=> Fix: get_icon_color respects highlight groups

lua/nvim-web-devicons.lua
Signed-off-by: David Ward <dward@redhat.com>
I chose a brain [1] icon because Drools [2] is a business intelligence rules engine language (of which I am the team's engineering manager at Red Hat). I wish Nerd Fonts had an actual "Drools" logo, but alas, it doesn't.
I chose a light pink [3] color because it will stand out better on light or dark backgrounds than using a white or gray color, I think. But I'd listen to other suggestions that might be better.
[1] search for "nf-fae-brain" here: https://www.nerdfonts.com/cheat-sheet
[2] https://www.drools.org/
[3] search for "LightPink1" here: https://www.ditig.com/256-colors-cheat-sheet
=> added light pink brain icon for Drools Rules Language (.drl)

lua/nvim-web-devicons.lua
Signed-off-by: David Ward <dward@redhat.com>
This is a follow-up to https://github.com/kyazdani42/nvim-web-devicons/pull/136 , which admittedly I messed up testing the plugin correctly by having mixed-up paths. I have verified this is now correct. Apologies.
=> fixed drools filetype to drools icon (extension) mapping

lua/nvim-web-devicons.lua
Previously `opts.default = false` gets overridden by `global_opts.default = true`
Now `opts.default` always overrides `global_opts.default`
=> default = false local override fix

lua/nvim-web-devicons.lua
So, this isn't quite ideal since nerd fonts don't include the GraphQL logo, but i was tired of seeing the default icon for my gql file and decided to do something about it.
This solution is basically just a recoloured react icon, but given that they are reasonably close you actively have to look to tell, which shouldn't much of an issue on reasonable font sizes.
If you don't think this should be core, I'll gladly leave it as a local tweak in my config :)
=> Icons: Add GraphQL support

lua/nvim-web-devicons.lua
Neovim's [`0.8` release](https://github.com/neovim/neovim/releases/tag/v0.8.0) added `query` as a separate filetype from scheme.
I added a little tree to signify it :)
note: I can just link it to scheme if that's more appropriate.
=> Add `query` icon

lua/nvim-web-devicons.lua
`build.sbt` files are `Scala` filetypes also. In scala projects they are used for building.
I tested this change in my local neovim install. Scala icon displayed for `.sbt` files correctly.
=> Add support for .sbt files which are scala files

lua/nvim-web-devicons.lua
This PR adds icons for `.tf` and `.tfvars`.
I considered `nf-fae-mountains ()`  vs `nf-mdi-terrain (行)` but decided to use the former since it's only 1 character wide.
=> Add terraform icons

lua/nvim-web-devicons.lua
This updates the kotlin logo to use the official color of the one-color logo that can be found [here](https://kotlinlang.org/docs/kotlin-brand-assets.html).
=> Update kotlin logo color

lua/nvim-web-devicons.lua
Vim recognizes `Containerfile`s as the `dockerfile` filetype. Since they can share the icon with Dockerfiles, I didn't add a separate filetype for them. If that's insufficient, let me know and I'll change it.
=> Add support for "Containerfile"

lua/nvim-web-devicons.lua
Map `.gql` to same icon as `.graphql` as it is common to use the alternative filetype
=> feat: map gql

README.md, lua/nvim-web-devicons.lua
This option allows to strictly select icon by filename or by extension, to prevent cases when filename happens to match some extension.
Closes #194
=> feat: Add `strict` option

lua/nvim-web-devicons.lua
I saw this https://github.com/nvim-tree/nvim-web-devicons/pull/191 and I like the idea of supporting `*.test.js`, `*.stories.tsx`, etc because these are quite common conventions.
The problem is currently this is not working as intended. (Only `test.js` highlights but not `foo.test.js`)
This PR is to fix this issue.
*Note*
Whether a plugin can reflect this change depends on the plugin's implementation.
(I see some attempt to support option to switch the way to get icons like this PR: https://github.com/akinsho/bufferline.nvim/pull/669)
=> fix: support ext convention

lua/nvim-web-devicons.lua
The old Docker icon is nearly invisible in dark background
This PR brings a new modern current Docker icon and adds some related file names also.
<div>
</div>
=> feat: use modern Docker icon

lua/nvim-web-devicons.lua
This PR adds an icon similar to the one in VSCode for `test.ts` and `spec.ts` files.
=> feat: add test.ts and spec.ts icon

lua/nvim-web-devicons.lua
Something that really bothered me when I was switching from vs code is no color distinction between .jsx and .tsx icons.
I can imagine frontend developers care about it more than backenders though :)
Before:
After:
=> feat: jsx and tsx icon colors

lua/nvim-web-devicons.lua
I like that someone has finally added test.ts files, but I think we're missing some consistency now especially for react enthusiasts ;)
So here I come with the setup that I had on my config files (this is what VS Code users would normally get by default).
Before:
After:
=> feat: js/ts/jsx/tsx consistent test/spec icons

lua/nvim-web-devicons.lua
Fixes https://github.com/nvim-tree/nvim-web-devicons/issues/44
This updates all the icon mappings to be fully lower case and then sanitizes the name passed in to `get_icon` to be lowercase as well. This makes the plugin now case insensitive to better support variations in filename casing.
=> Normalize case

lua/nvim-web-devicons.lua
fixes: https://github.com/nvim-tree/nvim-web-devicons/issues/206
I took @gegoune's approach on this comment (https://github.com/nvim-tree/nvim-web-devicons/issues/206#issuecomment-1436045476)
Before
After
(Note that I have set the custom icon on my config for `.stories.tsx` )
=> fix: handle extension with multiple dots

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
There's now a proper icon for Crystal in nerdfont, so we should use that instead. (Refer #68 for the initial icon)
This PR also changes the color in dark theme, as the current one `#000000` is really bad in visibility. The new dark theme color is taken from [vscode-icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#crystal).
=> fix: update icon for crystal

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
Reverts nvim-tree/nvim-web-devicons#231
It's because my symbol nerd font was out of date, when I updated it the icon shows up correctly. Although both icons do the job just fine given my PR was based on incorrect assumptions it should be reverted.
=> Revert "fix: Update icon for XML"

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
=> fix: fortran/fsharp file icons

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
Nim's offical icon is supported meanwhile. I thought we could use it.
=> feat: use official icon for `nim`

.github/workflows/lint.yml, lua/nvim-web-devicons.lua
Use jobs directly instead of through pre-commit.
=> ci: drop pre-commit from lint workflow

README.md, lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
Nerd Fonts 3 changed code points of some icons, this updates it according  to table [here](https://github.com/ryanoasis/nerd-fonts/issues/1059)
This will break everyone being on Nerd 2, but without it everyone on version 3 is broken also...
fixes #265
=> fix: update to Nerd Fonts 3 code points

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
=> feat: add bazel icons

lua/nvim-web-devicons.lua
Fix #226.
Now the icon color variant will change correctly according to current background when user sets the background inside neovim process.
- Before this commit:
1. On entering nvim: (correct) ![image](https://github.com/nvim-tree/nvim-web-devicons/assets/76579810/416b5281-01e9-4821-b519-d665c43bd351)
2. After `:set bg=light` light icon for light background   :( ![image](https://github.com/nvim-tree/nvim-web-devicons/assets/76579810/e789feb8-7c31-4a1f-87a0-d66336f23b07)
3. After `:set bg=dark` dark icon for dark background   :( ![image](https://github.com/nvim-tree/nvim-web-devicons/assets/76579810/38a935c6-6094-4375-8b5d-dca0c502e223)
- After this commit:
1. On entering nvim ![image](https://github.com/nvim-tree/nvim-web-devicons/assets/76579810/fa6a2a25-5150-4059-9f3e-8b6b2ee635be) …
=> fix(#226): allow override hlgroups when background changes

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
The previous icon was just a thunder. Added correct icon
=> fix: correct zig icon f0e7->e6a9

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
This uses the svelte icon for the `svelte.config.js` file.
Many other editors assign specific icons to configs of a framework and I think this should be done here as well.
=> feat: svelte config icon

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
I copied the icon that is used for the `.ts` extension
https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
=> feat: add `.cts` and `.mts` icons

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
Seeing it in the wild more and more, and using it myself. This format is here to stay.
I've used the properties shared by other image formats.
=> feat: add avif filetype

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
This updates the icon for Prisma to the official icon from Nerd Fonts: `e684`
=> feat: update prisma icon

lua/nvim-web-devicons-light.lua, lua/nvim-web-devicons.lua
Currently, it will only display for `*.r` files. This adds support for `*.R` files. It is common to capitalize `R` for R scripts.
- https://cran.r-project.org/doc/manuals/r-release/R-exts.html
=> fix: add missing icon for R language

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
More python related entries:
- `py.typed` and `.pyi` are [Python type annotation files](https://peps.python.org/pep-0561/#partial-stub-packages)
- `.pyx`, `.pxi` and `.pxd` are [Cython sources](https://cython.readthedocs.io/en/latest/src/userguide/language_basics.html#cython-file-types). Cython is considered as different language in vim (`filetype=pyrex`), but still belongs to Python family, so bluish color is used instead of yellow in original Python files.
=> feat: Icons for Python type annotation and Cython source

lua/nvim-web-devicons.lua
Having all functions local and returning only a subset was a bit confusing to me. Now all just makes more sense and is more standard.
=> refactor: explicit distinction between private and public functions

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
(This might be a bit opinionated)
Switch to using Ethereum project icon `nf-seti-ethereum` instead of Ethereum currency icon `nf-md-currency_eth` for solidity files.
Ideally, the solidity icon itself should be used but that is not available in the nerd fonts. But the current currency icon used does not make a lot of sense.
Thanks!
=> fix: correct solidity icon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua, scripts/generate_colors.lua
I noticed that some icons don't have a `cterm_color` value, so I updated the script to generate it if it's missing.
=> ci: generate cterm color even if line is missing

.github/workflows/lint.yml, .gitignore, CONTRIBUTING.md, Makefile, scripts/generate_colors.lua
Make started failing unpredictably for me. It could be a result of my setup, as we are running the user's full nvim setup.
* Run with `--clean`
* Clone `lifepillar/vim-colortemplate` if needed
* Fail hard
* Simplify CI to use make
Ran out of energy refactoring the ci further...
=> ci: harden generation

.github/workflows/ci.yml, Makefile
Looks more like the nvim-tree CI.
* versions pinned
* uses make targets
* splits into three jobs - yes that starts 3 docker instances however it seems to be best practice
* runs on master
=> ci: split jobs and pin versions

.pre-commit-config.yaml
luacheck and colors now use make, which sets things up.
I'll tidy this and `pre-commit-autoupdate.yml` afterwards, for easier review.
=> ci: pre-commit just calls make

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Update the glyph to the proper logo, added in nerd-fonts#1129 and released as of 3.1.0
Search up the code point [here](https://www.nerdfonts.com/cheat-sheet)
=> feat: Update fennel icon to true logo

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Nerd fonts still does not have a luau icon, but at least let's keep the original color from the website: https://luau-lang.org/. Luau also supports a `.luaurc` file where you can configure some settings for analysis.
=> feat: luau color change and .luaurc

.gitignore, Makefile
It seems there was some recycling going on, which resulted in a git clone failure.
https://github.com/nvim-tree/nvim-web-devicons/actions/runs/6999365828
=> ci: download vim colortemplate tarball

.github/workflows/pre-commit-autoupdate.yml, .pre-commit-config.yaml
@gegoune I think I am getting this wrong.
The 'Pre-commit autoupdate' jobs have been passing, until I moved them to the makefile.
The jobs have been failing as `make colors` is called multiple times against all files. That has been reverted.
However it seems that the colors job has never been passing - it's not had vim-colortemplate in the runtimepath. It is marked as successful. This branch is at the last known good commit, with some rubbish in the job. It's passing: https://github.com/nvim-tree/nvim-web-devicons/actions/runs/7000075636
1. Do we need colors in the pre-commit hook or is CI enough?
2. How can we make them work, via make or other means?
=> ci: remove colors from pre commit

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Toml icon has been added recently since Nerd Font version `3.1.1`
Since the original logo has white background, white color is prefer to the original `#7E7F7F` to make it stand out from others. <img width="25" alt="Toml logo" src="https://github.com/nvim-tree/nvim-web-devicons/assets/42694704/4065bc50-a7a6-45fc-b408-be22bb0174d6">
=> feat: update `toml` icons

lua/nvim-web-devicons.lua, lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua, scripts/generate_colors.lua
#361 
There are a few things to call out here.
- This adds a completely new table to the return of `icons-default` and `icons-light` called `icons_by_operating_system`. This set of icons is added with the other icons to the lookup table that is generated during initialization of all devicons.
- This (currently) does not pass the provided make tests due to the addition of the new `icons_by_operating_system` attribute
- There are several icons that I am choosing to omit from this. The following list of icons were omitted as the provided icon by [nerdfonts cheat-sheet](https://www.nerdfonts.com/cheat-sheet) was not found when I pasted it into my terminal. I am currently using the patched version of [firacode](https://github.com/tonsky/FiraCode) so I suspect these various items are all in a …
=> feat: operating system icons

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
This updates the icon for JavaScript (js) to the official icon from Nerd Fonts: `f031e`
=> fix: update js icon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Update **cjs**(CommonJS) & **mjs**(ModuleJS) icons same as **js**(JavaScript) from official Nerd Font icon : `f031e`
=> fix: update cjs & mjs icons

lua/nvim-web-devicons.lua
Fixes #261, #287
> [!NOTE]
> This PR does not address the problem of overrides being unaware of light/dark modes. They are applied universally still. This functionality will have to be implemented later, but this PR is better than nothing.
=> fix(#261 #287): persist icon overrides when changing &background

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Previous `tsx` color was good but that color is a little bit darker. That's why using the same color as `jsx` for `tsx`
**Previous**
**Updated**
Add icon for filename  `tailwind.config.js` from official nerd fonts icon `f13ff`
=> feat: Add icon for tailwind config

lua/nvim-web-devicons.lua
The default icon should be in `get_icons()[1]` but it disappears after changing the background. This PR fixes the issue.
=> fix: `get_icons()[1]` being nil after changing &background

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
=> feat: add build.zig.zon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Fatal bug, introduced by #395 
Now it works as intended :D
**BUG:**
=> fix: remove space in zig object notation hl group

lua/nvim-web-devicons.lua, lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Icon for Nushell files https://www.nushell.sh/
- Color is Nushell's "Brand" color
- Icon is generic because Nerd Fonts don't include Nushell's chevron-like logo
=> feat: add nu

README.md, lua/nvim-web-devicons.lua
simply adds/updates user-defined filetypes to the internal filetypes table.
fixes #406
=> feat(#406): add set_icon_by_filetype

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Gives backup (`.bak`) files the backup restoration Nerdfont icon.
=> feat: add bak

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Replaces `nf-dev-rust` icon with `nf-md-language_rust` as it renders better on the Kitty terminal.
=> fix: update rust icon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Icon for Prettier Configuration
File: **.prettierrc**
Issue Resolved: #127 
Icon for Prettier ([This PR](https://github.com/ryanoasis/nerd-fonts/pull/1470#issuecomment-1996766537)) is merged yesterday to the official nerd fonts repo. Website is still not updated also you need to build font from master branch to actually view this icon
Feel free to change color of this icon. I don't have any good colors in my mind to add in this icon.
Here's a Screenshot
=> feat: add .prettierrc

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Do not merge both this and https://github.com/nvim-tree/nvim-web-devicons/pull/376
=> revert: back to seti: js, cjs and mjs

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Update tex icon from 󰙩 to 
fixes #435
=> fix(#435): tex icon

lua/nvim-web-devicons.lua, lua/nvim-web-devicons/hi-test.lua, lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua, scripts/generate_colors.lua
Bifurcation from #433 
I tried to use "official" color of the logos but the darker ones were adjusted a bit. dwm uses the suckless color.
I'm not sure what causes the error in Xterm, I need to look for a patched font to test there and urxvt, Symbols only fallbacks on Alacritty.
Does this PR causes also problem?
Fix #432
=> feat: add desktop environment and window manager categories with icons

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Glyph is the same as on it logo, a pinkish flame.
Edit: ~~I'll add a few more~~ DONE
- Should `cfg` extension should also use the gear icons as `conf` and `ini` files? also is a config file, currently uses   .
- I think we should use `#f54d27` color on git icons.
Fix #300
Fix #327
=> feat: add more icons, misc

lua/nvim-web-devicons.lua
Problem: `get_icon_color()` does not find icons for files whose names are capitalized and which don't have extensions, such as "LICENSE", "License", or "COMMIT_EDITMSG". This is inconsistent with the functionality of `get_icon()`, which does lowercase the name parameter.
Solution: Lowercase the name parameter in get_icon_color(). Coincidentally, get_icon() and get_icon_color() have a lot of duplicate functionality at the front of the function, specifically to get the entire icon data. Abstract this functionality out to a local function that can be shared by these other two functions, which are now wrapper functions that return different data.
=> fix: get_icon_color() is now case insensitive

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
- Change git color to #f54d27
- Use same icons for cfg, conf and ini files, using: 
- Add tmux config files 
- Add Tux icons to `a`, `ko` and `so` files
- Add Android icon to `android` and `apk` files
- Add down arrow icon for some download files
- Add library icon for `dll` and `lib` files
- Add Emacs icons for `el`, `elc` and `eln` files
- Add also env icon for `.env` files
- Add calendar icon for some files
- Add bin icons for `o` files
---
=> feat: add many icons, use official git colour

README.md
Added requested documentation
fixes #453
=> docs(#453): add known issue: Windows and WSL not rendering icons properly on some terminals

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
resolves #456, now gulpfile/gruntfile.js, .ts, .babel.js, .coffee will have their proper icons instead of standard JS icon
demo:
nvim-tree
telescope
bufferline
should work across all plugins that have nvim-web-devicons as dependencies
=> fix(#456): adding gulpfile/gruntfile extensions for js and other js types

lua/nvim-web-devicons.lua
fixes #465 
`set_icon` was not being added to `global_opts.override`
=> fix(#465): set_icon broken

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
The changes in the PR would add an icon for mojo.
- Used color is the linguist color
- Used icon is nf-md-fire as a font-icon looks better in the tree as a unicode emoji character and is less likely to set things off. If the emoji is the preferred choice, please let me know, I don't have a strong preference here.
=> feat: add mojo

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
The changes in the PR would update icon for `.bablerc` file and React File colors
- Update babelrc icon to `nf-seti-babel` (e639)
To diiferenciate between `jsx` and `tsx` files.  Changed `jsx` color to **yellow**. Because it will be easier to work with js and jsx files. TSX color changed to Previous JSX color
=> fix: update .babelrc icon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
#288 
```
stylua . --check
luacheck lua scripts
Checking lua/nvim-web-devicons.lua                OK
Checking lua/nvim-web-devicons/hi-test.lua        OK
Checking lua/nvim-web-devicons/icons-default.lua  OK
Checking lua/nvim-web-devicons/icons-light.lua    OK
Checking scripts/generate_colors.lua              OK
Total: 0 warnings / 0 errors in 5 files
```
=> feat: add .go.mod, .go.sum, .go.work

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
According to the documentation
> There are two tables where icons can be added:
> 1. icons_by_filename
> 2. icons_by_file_extension
>
> Add the icon in table 1. if the icon is for a file that is always named that
> way, for example `.gitconfig`. Add to table 2. if the icon is for all files
> with an extension.
the Gleam icon must be placed under `icons_by_file_extension`
Disclaimer: it was not working for me and that's the reason
=> fix(gleam): move from icons_by_filename to icons_by_file_extension

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Add vercel icon `▲` (U+25B2) so it should not need any special char added to a font.
I opened this but realized it's a dead repo 💀
https://github.com/vorillaz/devicons/pull/157
=> feat: add vercel

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Includes missing entries for the prettier config. 
Stumbled over it while using astro which defaults to `.prettierrc.mjs`
=> feat: add .prettierrc.{cjs,js,mjs}

README.md, lua/nvim-web-devicons.lua
PR for the discussion here: https://github.com/nvim-tree/nvim-web-devicons/discussions/491#discussioncomment-10649821
I have a few questions about the code. Right now, `refresh_icons()` is called directly in the `nvim-web-devicons.lua` file. However, now that I'm adding an option which the `refresh_icons()` function depends on, should I move the call into the `setup()` function? Right now im just calling `refresh_icons()` again if the variant option is not "auto", which is a bit inefficient.
=> feat: add variant="light|dark" option to override &background

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Feel free to change the icon and/or colors. I picked the colors from [this logo on wikipedia](https://en.wikipedia.org/wiki/HTTP?oldformat=true#/media/File:HTTP_logo.svg). I'm not sure how established it is though.
=> feat: add http

lua/nvim-web-devicons.lua
=> fix(#498): set_icons failed when called before setup

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Add's suport for hyprpaper (https://github.com/hyprwm/hyprpaper) config files, using the same config as the rest of the hypr suite.
=> feat: add hyprpaper icons

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Add icon for '.adb', '.ads', and '.gpr' file types.
=> feat: add adb ads gpr

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
This commit adds the bun icon for bun's lockfile (bun.lockb). The latest release of nerdfonts (v3.3.0) adds the bun icon.
Taken from [nerdfont cheat-sheet](https://www.nerdfonts.com/cheat-sheet)
=> feat: add bun.lockb

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Using new glyphs from Nerd Fonts 3.3.0 release: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.3.0
LibreOffice colors got from accent colors: https://wiki.documentfoundation.org/Design/Branding
```shell
touch .clang-{format,tidy} .condarc .luacheckrc .nanorc .pre-commit-config.yaml .pylintrc cmakelists.txt README{,.md} file.{cmake,conda,ipynb,typ,vala,vi}
touch file.{{f,}{odp,odt,ods,odg},odf}
```
This pull request includes a series of updates to the `nvim-web-devicons` plugin, specifically adding new file and operating system icons, and updating existing ones. The changes span across the `icons-default.lua` and `icons-light.lua` files.
| 1 | 2 |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/bebe1601-fe1b-4126-82cb-6844216f95c8) | …
=> feat: add many icons

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Changed color for the D programming language icon from dark green to the official dark red (#b03931), along with the cterm color to a similar dark red.
Edit: Light mode color has been updated to (#842b25), which was provided by the color check CI.
=> style: Update D lang color

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
=> fix: update `vercel.json` glyph from Unicode to Nerd Fonts

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Converted remaining unicode glyphs to nerd font:
```
: ; lua ../../../audit.lua | grep NOGLYPH
NOGLYPH-                  1/1 0x02699 ⚙ cpy
NOGLYPH-                  1/1 0x02699 ⚙ cob
NOGLYPH-                  1/1 0x0235d ⍝ apl
NOGLYPH-                  1/1 0x02699 ⚙ cbl
NOGLYPH-                  1/1 0x003bb λ signature
NOGLYPH-                  1/1 0x02389 ⎉ bqn
NOGLYPH-                  1/1 0xf0509 󰔉 material
NOGLYPH-                  1/1 0x0003e > nu
NOGLYPH-                  1/1 0x0221e ∞ mo
NOGLYPH-                  1/1 0x003bb λ sig
NOGLYPH-                  1/1 0x02699 ⚙ cobol
NOGLYPH-                  1/1 0x003bb λ sml
```
```lua
local lunajson = require "lunajson"
local icons_by_filename = require("icons-default").icons_by_filename
local icons_by_file_extension = …
```
=> chore: convert all remaining unicode to nerd font

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Fixes #510 
Updated the definitions of the `gemfile` and `vagrantfile` by removing the unused `$` sign.
=> fix: update Gemfile and valgrant files incorrect definitions

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
AUTHORS is common on some projects and `index.theme`[^1] appear on icon themes like MoreWaita
[^1]: https://specifications.freedesktop.org/icon-theme-spec/latest/
=> feat: add icons for AUTHORS{,.txt} and index.theme files

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Added icon for the new dotnet solution file format. Slnx. This also represents a solution as the normal .sln extension so it makes sense to give it the same icon
reference: https://github.com/vim/vim/pull/16334
=> feat: add slnx icon

lua/nvim-web-devicons/icons-default.lua, lua/nvim-web-devicons/icons-light.lua
Adds icons for msbuild configuration files
reference: https://github.com/vim/vim/pull/16339
=> feat: add msbuild configuration icons

lua/nvim-web-devicons.lua
We should raise the minimum version of nvim to 0.9 or 0.10 at some point
=> chore: replace deprecated neovim API

lua/nvim-web-devicons/default/icons_by_file_extension.lua, lua/nvim-web-devicons/light/icons_by_file_extension.lua
add  icon for .dockerignore extension
=> feat: add .dockerignore icon

.pre-commit-config.yaml, lua/nvim-web-devicons.lua, lua/nvim-web-devicons/filetypes.lua
Resolves https://github.com/nvim-tree/nvim-web-devicons/issues/572
Git diff maybe result a little bit confusing, but I only extracted `apply_user_icons()` from `setup()`, so it can be called also later during the `refresh` callback.
=> fix: ensure icon overrides apply after refresh

.pre-commit-config.yaml, lua/nvim-web-devicons.lua, lua/nvim-web-devicons/filetypes.lua
Resolves #572 (original issue)
Resolves #575 (reported bug)
I reapplied the changes from #572.
In addition, I fixed the reported bug with 37078ee42c620f63d0d3465b39515bec31d81975.
I configured locally the plugin so I simulate I "require" the plugin from other plugin as dependency, but without calling "setup". 
```lua
return {
'nvim-tree/nvim-web-devicons',
dir="/Users/dsaenz/Code/nvim-web-devicons",
dev = true,
config = function()
require'nvim-web-devicons'
end
}
```
With this, when I open NeoVim I got exactly the same error reported by the user:
Because `setup` was not called, `user_icons` was not initialized properly. As result, calling `apply_user_icons` from the auto command was 🧨 .
=> fix(#572, #575): ensure icon overrides apply after refresh

lua/nvim-web-devicons/default/icons_by_filename.lua, lua/nvim-web-devicons/light/icons_by_filename.lua
This PR adds an icon for [`Jenkinsfile`](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/).
The icon uses the Jenkins Nerd Font glyph, with the color chosen to match the bowtie (and background) from the official Jenkins logo.
I also considered going for white (`#FFFFFF`), but I'm not sure if it looks better, let me know if you prefer the white version, so I could change it.
=> feat: add Jenkinsfile Icon
