nvim-tree/nvim-web-devicons

README.md

Add an initial `README` explaining how this plugin works. Closes #5

Add WIP Readme

---

lua/nvim-web-devicons.lua

icons: change default

---

README.md
lua/nvim-web-devicons.lua

add user config

---

README.md
lua/nvim-web-devicons.lua

add setup check

---

lua/nvim-web-devicons.lua

Need to display a git logo. The color comes from their official logo.

feat: add git logo

---

lua/nvim-web-devicons.lua

use api.nvim_command instead of vim.cmd to be 0.4 compatible

---

lua/nvim-web-devicons.lua

enable overriding default icon

---

lua/nvim-web-devicons.lua

I don’t know what other people think, but I like to start my nvim quickly

perf: defer highlighting to reduce first load time

---

lua/nvim-web-devicons.lua

Add pdf icon from nerd font: ;
(Ignore the Github rendering, this is not a dollar sign.)

Add pdf icon

---

lua/nvim-web-devicons.lua

This is related to #44. Not sure if it closes it.

Add icons for "R" and "Rmd" extensions.

---

lua/nvim-web-devicons.lua

Add Svelte icon

---

README.md
lua/nvim-web-devicons.lua

Add methods to enable icon overrides after setup has been called

---

README.md
lua/nvim-web-devicons.lua

feat: add set_default_icon function

---

README.md

Add get_icon_color to README

---

lua/nvim-web-devicons.lua

added icon for mint filetypes , https://www.mint-lang.com/

add icon for .mint

---

README.md
lua/nvim-web-devicons.lua

this will set ctermfg as well to support terminal vim that doesn't support guifg

add cterm support

---

lua/nvim-web-devicons.lua

Added Sqlite, Sqlite3, Sublime icons, and fixed the py, pyc, pyo, pyd icon colors.

Added and fixed some icons

---

lua/nvim-web-devicons.lua

- remove duplicates
- brewfile, txt
- remove semicolons and replace with commas
- add "csv" entry, same as "txt"

chore, feat(nvim-web-devicons.lua):

---

lua/nvim-web-devicons.lua

- sort "icons" associative table by key name
- apply stylua formatting to some parts of src
- add spaces around concatenation
- spread some long lines across multiple lines
- remove stray semicolons

style(nvim-web-devicons.lua): sort entries

---

lua/nvim-web-devicons.lua

feat: add solidity icon

---

lua/nvim-web-devicons.lua

feat: add fennel icon

---

lua/nvim-web-devicons.lua

Added icons for the motoko language ( from dfinity ) . PS i really wanted some motoko icons for my neovim :heart: :fire:

added icon for motoko language

---

lua/nvim-web-devicons.lua

Not the original feather, but better than nothing.

Add icon for tcl/tk.

---

lua/nvim-web-devicons.lua

Setting color_icons to false will make all highlights follow the default icon
Closes #109

Added global option `color_icons`

---

lua/nvim-web-devicons.lua

- Added Scheme icon
- Updated Kotlin and KotlinScript (latest nerd-fonts release required)
- Fixed previous PR (json5 filetype)

Icon updates

---

README.md
lua/nvim-web-devicons.lua

- Utilizes nvim api more as it is cleaner and more performant
- also localizes some frequently api functions
closes #169

Utilize nvim api more

---

lua/nvim-web-devicons.lua

Add JS icon but in orange for test JS files (eg: App.test.js) like vs-code.

Add *test.js orange color for react like vs-code

---

lua/nvim-web-devicons.lua

feat: add wasm icon

---

lua/nvim-web-devicons.lua

add other common names for makefile

---

lua/nvim-web-devicons.lua

feat: add liquid(Shopify) icon

---

lua/nvim-web-devicons.lua
scripts/cterm-colors-generator.lua

Recalculated with the algorithm from lifepillar/vim-colortemplate, that gives better approximations.

feat: more accurate cterm colors

---

lua/nvim-web-devicons.lua

fixes #220 
tested https://github.com/nvim-tree/nvim-web-devicons/issues/220#issuecomment-1457199526

fix(#220): get_icon allow nil name

---

README.md

Ref:
https://github.com/nvim-tree/nvim-web-devicons/blob/0568104bf8d0c3ab16395433fcc5c1638efc25d4/lua/nvim-web-devicons.lua#L2006

Update README: Fix signature of `set_default_icon`

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add cjs icon

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add rescript icon

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add vlang .vsh

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add jsonc support

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

This adds an icon for `.editorconfig`.

feat: EditorConfig icon

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

[Huff Lang Website](https://huff.sh/)

feat: add huff icon

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add Dockerfile extension

---

lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

feat: add .hurl icon

---

CONTRIBUTING.md
lua/nvim-web-devicons-light.lua
lua/nvim-web-devicons.lua

This would still need the other PR merged in. Also I am not sure whether the icons are case sensitive or not. If they are not, we might also want to remove the upper case ones.

chore: reorder icon entries alphabetically

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

fix(#329): add `compose.yaml` and `compose.yml`

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

see https://www.r-project.org/logo/Rlogo.svg.
The official color is a gradient, but I picked a spot in the middle.

fix: correct R icon color from green to R-langs blue

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

https://github.com/nvim-tree/nvim-web-devicons/pull/351#issuecomment-1866252468

fix(exe): invalid hex value

---

lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

feat: Add icons for templ files

---

scripts/generate_colors.lua

See https://github.com/nvim-tree/nvim-web-devicons/pull/351#issuecomment-1866285143
Checks that #rrggbb is correct length

ci: ensure color is valid length #rrggbb

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Same with vscode icons, `.eslintignore` file icon as same as `.eslintrc`

feat: eslintignore icon

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Closes #371
It looks way cleaner!

feat: update `.tf` icon #371

---

.github/workflows/release.yml
README.md

ci: luarocks release plumbing

---

lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

tried to add a [haxe](https://haxe.org/) icon, still isn't showing for me though

feat: add haxe

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

feat: add C++20 extentions

---

lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

This PR adds an icon for `:checkhealth`

feat: add checkhealth

---

CONTRIBUTING.md
README.md
lua/nvim-web-devicons.lua
lua/nvim-web-devicons/hi-test.lua

feat(#192): :NvimWebDeviconsHiTest

---

README.md
lua/nvim-web-devicons.lua
lua/nvim-web-devicons/hi-test.lua

fix(#419): harden HiTest, add missing override_by_operating_system

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Add icon for scala script files, using the existing scala icon.

feat: add sc

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

feat(#452): differentiate .d.ts and .ts

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Add icon for node version manager files:

feat: add .nvmrc icon

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

`just` accepts `justfile` and `.justfile`, therefore adding both. https://just.systems/man/en/chapter_57.html?highlight=.justfile#hiding-justfiles

feat: add Justfiles

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

- Use Git color on `.mailmap` file
- Add `.git-blame-ignore-revs` file
- Add Python icon to `.pyw` file extension
- Add `robots.txt` file

feat: add git-blame-ignore-revs, robots.txt, fix pyw icon, update mailmap colour

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Closes #463
Adds a pink start reflecting [Gleam's logo/mascot](https://gleam.run/) for `.gleam`

feat: add gleam

---

lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

This pull request adds icons for the APL and BQN filetypes. That's it. 
For regular users of the language, this will be a nice touch.

feat: add apl bqn

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

feat: add ebuild file extension

---

README.md
lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

fixes #502 
I'm always nervous about fixes like this... is this safe @hasecilu ?

fix(#502): explicit case insensitive matching of filenames

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

fix(#505): add missing 'R' extension

---

README.md

docs(#516): README: full description

---

lua/nvim-web-devicons.lua
lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

feat: add Odin language icon

---

lua/nvim-web-devicons/icons-default.lua
lua/nvim-web-devicons/icons-light.lua

Source: https://cucumber.io/docs/
With light theme
With dark theme

feat: Add Cucumber .feature file icon

---

.github/ISSUE_TEMPLATE/feature_request.md

Types work really well, nvim-tree could do with the same treatment:
https://github.com/nvim-tree/nvim-web-devicons/issues/555
https://github.com/nvim-tree/nvim-web-devicons/issues/556
Feature was incorrect.

chore: correct type for feature request

---

.github/ISSUE_TEMPLATE/bug_report.yml

I considered adding a field for font/version however I'm not sure how to ask that: there are many ways to install a nerd font.

chore: add more details to bug report: before reporting

---

lua/nvim-web-devicons/default/icons_by_filename.lua
lua/nvim-web-devicons/light/icons_by_filename.lua

hyprlandd.conf is a debug config used when compiling hyprland with the debug target

feat: add hyprlandd.conf

---

lua/nvim-web-devicons/default/icons_by_file_extension.lua
lua/nvim-web-devicons/filetypes.lua
lua/nvim-web-devicons/light/icons_by_file_extension.lua

feat: add icon for rasi
